server:
  port: 8080

spring:
  cache:
    type: redis
    redis:
      time-to-live: 3000000
  redis:
    cluster:
      nodes:
        - cortex-0002-001.8xmvap.0001.use1.cache.amazonaws.com:6379
        - cortex-0002-002.8xmvap.0001.use1.cache.amazonaws.com:6379

clients:
  BCB:
    host: "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata"
