server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cambiodb}
    username: ${DB_USER:cambio}
    password: ${DB_PASS:6RCEGQmA}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

logging:
  level:
    com:
      br:
        cortex:
          cambio:
            infra:
              client:
                BCBClient: DEBUG
