server:
  port: 8081

spring:
  cache:
    type: redis
    redis:
      time-to-live: 10
  redis:
    host: localhost
    port: 6379

clients:
  BCB:
    host: "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata"
